# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,\
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import argparse
import sys
import os
from mpmath import mp, zeta, __version__ as version
parser = argparse.ArgumentParser(description="Program to compute zeta(s, a).")
parser.add_argument("data", type=str, help="s, a values")
args = parser.parse_args()
mp.dps = 36
mp.pretty = True

with open(args.data) as f:
  for line in f:
    line = line.strip()
    if not len(line) or line[0] == '#':
      print(line)
      if 'Generated by' in line:
        print(f'# Evaluated using {os.path.basename(sys.argv[0])}')
        print(f'# mpmath ({version}) zeta(s, a)')
      continue
    i = line.index(',') # raise error if not found
    s, a = float(line[0:i]), float(line[i+1:])
    print(f'{s}, {a}, {zeta(s, a)}')
